Documentation for the Controllers folder + minor detail for previous docstrings
Illuminator-team/Illuminator pull request #31
Opened 2024-09-03 12:51 UTC by jgrguric96

This PR primarily contains the addition of docstrings for the files within the Controllers folder.
It also contains some small additions for the Agents folder files (such as type hints)

Luckily, a lot of context needed for the documentation was already done by mosaik itself with the requirements they have when inheriting the mosaik_api.Simulator class.

The missing docstring details can be expanded upon at a later date.

2024-09-03 12:53 UTC, jgrguric96 commented on Agents/prosumer_mosaik.py
> +            The size of the time step. The unit is arbitrary, bit it has to be consistent among all simulators used in a simulation.
I already see a typo I made 👎

2024-09-06 09:14 UTC, manuGil requested changes
Thanks for writing the doc strings. Please read my comment on specific files. 
After that you can merge the changes. As a follow up, we should ask researchers to review and complete the missing information.

2024-09-06 09:14 UTC, manuGil commented on Controllers/ResidentialController/controller_mosaik.py
> +        Constructor for the controlSim class with the mosaik_api.Simulator class as its Parent class
Read my comment on redundancy in the doc strings, and correct things across files

2024-09-06 09:14 UTC, manuGil commented on Games/p2ptrading_mosaik.py
> +        Because this method has an additional parameter `step_size` it is overriding the parent method init().
overwriting?

2024-09-09 08:37 UTC, merged